# Generated by Django 3.0.4 on 2020-03-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=120)),
                ('definitionWord', models.TextField()),
                ('definitionOther1', models.TextField()),
                ('definitionOther2', models.TextField()),
                ('definitionOther3', models.TextField()),
                ('definitionOther4', models.TextField()),
            ],
        ),
    ]
